name = "ABMExamples"
uuid = "e197a762-bdbf-4f9a-9098-3a995a6524ed"
authors = ["Code Komali <code.komali@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
